export interface PendingTask {
  fmsName: string;
  company: string;
  url: string;
  totalPending: number;
  delayCount: number;
  age: number;
  pcName: string;
  doerName: string;
  important: boolean;
  timestamp: string;
  dmeName: string;
}

export const pendingTasksData: PendingTask[] = [
  {
    "fmsName": "V2. FMS- Enquiry Cold Reverification",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1t2OqrWmevCPAIhR4DzvnYqj95Xp7Q6qTQiP9b_8fbFw/edit?gid=1151878438#gid=1151878438",
    "totalPending": 41796,
    "delayCount": 41721,
    "age": 304,
    "pcName": "Kavita",
    "doerName": "Vikash,Rohan Babbar,Anupam Singh Molpha,Astha Kumari",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:32:37",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "V3.0 New - KTAHV CLIENT BOOKING FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1eTEsMwgIWqSGJ2FOiyQ42AegJ81dywaiwHo7ynVbJXE/edit?gid=350204962#gid=350204962",
    "totalPending": 309,
    "delayCount": 301,
    "age": 545,
    "pcName": "Kavita",
    "doerName": "Shoukath Ali Moosa,Nishant,Pushpanshu Kumar,Pawan Kamra,Sadik Rehman,Admin,Harpal Singh,Suresh Kumar c",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:37",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "KTAHV Daily Checkedin Master FMS - Resort V3 - Riya Sharma",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1iQALo4lMU5CjqLJMi28onM5D5XWkcz4JCMDs6hiEC6E/edit?gid=1956925619#gid=1956925619&range=BB11",
    "totalPending": 13,
    "delayCount": 5,
    "age": 13,
    "pcName": "Kavita",
    "doerName": "Shoukath Ali Moosa",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:38",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "KTAHV CAPA FMS - Resort V3",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1c6Q4VSBWazVlgxUOvAbn9-4EQOKG5zwIq_lDAvGVTxY/edit?gid=1807322639#gid=1807322639",
    "totalPending": 49,
    "delayCount": 49,
    "age": 403,
    "pcName": "Kavita",
    "doerName": "Nisha G,Shoukath Ali Moosa,Biju.R,Vibin S,Abilash A,Bonny Thomas,Abhilash Sir,Sanju U",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:39",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Doctor Consultation FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/18CrIJ7OQq-UojeQfxWRhAFFsPF4dUT6G2JMOJQf5B7I/edit?gid=1459019157#gid=1459019157",
    "totalPending": 47,
    "delayCount": 43,
    "age": 32,
    "pcName": "Kavita",
    "doerName": "Shona George,Dr Deepu John",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:41",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Daily SALES Reports Log FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1CJIL3mtqU5VYCB2AWJGMcSp_uOX8ErhBXoiAl9E4BFU/edit?gid=0#gid=0",
    "totalPending": 397,
    "delayCount": 390,
    "age": 22,
    "pcName": "Krithika",
    "doerName": "Sadik Rehman,Pushpanshu Kumar,Dhaneshwar Chaturvedi",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:42",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "SADIK - Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1vtPgK0aePBG2-0LFW1Om3huI9o-izcUAFlwgGD3c5cQ/edit#gid=93793889&range=N7",
    "totalPending": 201,
    "delayCount": 28,
    "age": 5,
    "pcName": "Kavita",
    "doerName": "Sadik Rehman",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:44",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "PAWAN - Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1RmFofCUShgNptcuILqRDnyhiMQkvrsG4_BStWTjXOKE/edit#gid=93793889&range=N8",
    "totalPending": 25,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Pawan Kamra",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:44",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Payal - Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1c26gS3R1iOqWce9kGlXKv8g3pq25QHlWJ5WNwarPzQg/edit?gid=93793889#gid=93793889&range=N111",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Payal",
    "important": true,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "PUSHPANSHU - Calling Enquiry FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1DdvlR66XL8TxjtO3IR6bHleb2iuljFRm2j1BkHnvDGA/edit#gid=93793889&range=N7",
    "totalPending": 84,
    "delayCount": 15,
    "age": 6,
    "pcName": "Kavita",
    "doerName": "Pushpanshu Kumar",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:34:46",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "SquardVoice Call Audit FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1WdOT0XGBRRvUgUq2YIXPNeFMfp4zquQMGgHlna3dZBk/edit?gid=1278086012&range=BJ10",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Himanshu",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Vidisha Bahukhandi- Calling Enquiry FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1XJt9c8PcTeq-tneg8oADe-AVnTW0nosePhfw8-YW62Y/edit#gid=93793889&range=N7",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Vidisha Bahukhandi",
    "important": true,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Sana Albi - Calling Enquiry FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1vPnUI0nsbI0IUmxgWjD68iOFKIbehT6mVmmkftyjYsY/edit?gid=507747069#gid=507747069",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Sana Albi",
    "important": true,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Astha Kumari - Calling Enquiry FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1448ljOH3AHytlM90EEc-p7qUyb8CoGnvEOXlyUc6cm0/edit?gid=93793889#gid=93793889&range=N7",
    "totalPending": 20,
    "delayCount": 20,
    "age": 76,
    "pcName": "Nisha Tripathi",
    "doerName": "Astha Kumari",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:34:55",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Bhuvaneshwari - Calling Enquiry FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1TiOzFNoKdUJANHkXWyVHv5swYVTDrfLgQ8U7qxaLWx8/edit#gid=550158905&range=N16",
    "totalPending": 96,
    "delayCount": 11,
    "age": 16,
    "pcName": "Kavita",
    "doerName": "Bhuvaneshwari",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:34:57",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Himanshu - Calling Enquiry FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/12zgv6EAV7pvjgG3x3PPX8MAtXEXhuqY3L5OdeBmIfNo/edit#gid=93793889&range=N9",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "New - Enquiry Calling Sheet - HR",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1iO0c17JIFbGPNwwGDzoxhSSO3_YTm9S_K3vxDHXM_W4/edit#gid=93793889&range=N84",
    "totalPending": 774,
    "delayCount": 249,
    "age": 49,
    "pcName": "Nisha Tripathi",
    "doerName": "Dhaneshwar Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:03",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Content Management System FMS (CMS)",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/13hyOIrYWKPmmqRopphgGXrXBOu5ThwVRlLw124pbA6g/edit?gid=1712884154#gid=1712884154",
    "totalPending": 110,
    "delayCount": 103,
    "age": 70,
    "pcName": "Nisha Tripathi",
    "doerName": "Anupam Singh Molpha,Astha Kumari,Roshni A John,Varun Chauhan",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:35:04",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "POB New Order FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1nMimTWEvVMzupUED58JKEP_imsy3yfvVNSO0LYdUaSY/edit?gid=0#gid=0",
    "totalPending": 9,
    "delayCount": 9,
    "age": 1,
    "pcName": "Krithika",
    "doerName": "Sanjay Yadav",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:35:04",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "POB Cancel Order FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/13UkySjTtJT210UCHWxPwn25qFDvHmHRcs15wGH_lydg/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Anuj Kumar Singh",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Costing Review FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1J17ADExIvGd8WNFODQtouhv9kWnU9aPzPnaMbazmwtg/edit#gid=1273448340",
    "totalPending": 188,
    "delayCount": 183,
    "age": 134,
    "pcName": "Krithika",
    "doerName": "Hariharan",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:10",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "POB Collection FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1AibDYDIkWKDc0dtlPkehNvp57oKZwMlul0wUcmHM6nk/edit#gid=464334775",
    "totalPending": 832,
    "delayCount": 218,
    "age": 35,
    "pcName": "Krithika",
    "doerName": "Kavita Mahawar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:15",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Filling PMS (Ayurvedic & Sanitizer)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1uVBhIBZUgNzG4ACljsLs4iqi0N5CM5lv3Nj3jVr7xw0/edit#gid=892478979",
    "totalPending": 159,
    "delayCount": 159,
    "age": 158,
    "pcName": "Krithika",
    "doerName": "Sakthivel S,Balakrishna",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:16",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Employee OneThing-BreakThrough-BreakDown FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1ot5HgGbaHKdz3Ya38VTz_m3_EqTKu6FKce7_yQB7DE0/edit#gid=0",
    "totalPending": 323,
    "delayCount": 323,
    "age": 19,
    "pcName": "Krithika",
    "doerName": "Zaki Ahmed,Pushpanshu Kumar,Sadik Rehman,Geethanjali,Suriya Prakash,Biju,Muthukumara Raja,Dhaneshwar Chaturvedi,Rahul R,Harpal Singh,UDHAYANANDHINI A,Santhosh,Astha Kumari,Anupam Singh Molpha,Deepu Sahani,Dr. Akhila Oommen,Ashikha Raj,Shailesh Kumar,ANAGHA S,Rajalakshmi K,Hariharan,Ajay,Ambuj,Satyam Kumar,Roshni A John,Pawan Kamra,Silpa V,Thangarasu,Vikash,Manonmani,Ritu Chawla,Sunaj Sahoo,Bhuvaneshwari,Jobin Abraham,Arul,Karan Pahuja,Varun Chauhan,Nisha Tripathi,Krithika,Nagendran,Kavita Mahawar,Levil Kumar,Shoukath Ali Moosa,Abhijeet Chandra,Sanyam Jain,Achanya B,Rakesh RajaGopal",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:16",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Purchase Follow Up FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1SdFBlcWnZGPQfjQ2nQ-CcSrw7qqIDNVnIn2impf5TPc/edit#gid=0",
    "totalPending": 192,
    "delayCount": 120,
    "age": 61,
    "pcName": "Krithika",
    "doerName": "Nagendran",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:38",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "New Vendor Development (NVD)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1mcuBL9FmQVdZcOj-1Pg71JKTnIqPoJqDghfTtJVYRYY/edit#gid=170376025",
    "totalPending": 233,
    "delayCount": 233,
    "age": 73,
    "pcName": "Krithika",
    "doerName": "Bhuvaneshwari",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:41",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Marketing FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/177Pl5InZDG4MxhJppK_xq9ZZDudi2xVH2UXbm2UUXAk/edit#gid=222097689",
    "totalPending": 85,
    "delayCount": 83,
    "age": 489,
    "pcName": "Nisha Tripathi",
    "doerName": "Abhilash Sir,Anupam Singh Molpha,Puneet Endlay,Astha Kumari",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:35:45",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Materials Issuing FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/184qRjNp93QAqOf2ba0VtnZTDOY6abiIBPuzVhZsJnCo/edit#gid=1176464765",
    "totalPending": 153,
    "delayCount": 92,
    "age": 50,
    "pcName": "Krithika",
    "doerName": "Sakthivel S,Hariharan",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:41:15",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Clients Blacklisting FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1EnK4XAOsr3u_1zeXtdhkP71dTfKP2OIyLaEyfAKqqQI/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Karan Pahuja",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Distributor OnBoarding FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1n7x53p2LnaapvcPQhhybb04V_O0Pd7DGtYowVdz0eQg/edit#gid=855232229",
    "totalPending": 2,
    "delayCount": 2,
    "age": 322,
    "pcName": "Krithika",
    "doerName": "Sunaj Sahoo,Dhaneshwar Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:36",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "New - Enquiry Calling Sheet - Puneet Endlay",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1_s092tYs4y4Ez3IZUBDivzk1E-coeMLsMHLPMx_C52c/edit#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Puneet Endlay",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "POB Reorder (Actual) - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1UqKxwiNhmgAvjHnDD4uinUE7dC_QucT68IHuUPIAWYk/edit#gid=0",
    "totalPending": 358,
    "delayCount": 342,
    "age": 72,
    "pcName": "Krithika",
    "doerName": "Ravi Mishra,Krithika",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:37",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "HELPTICKET v2",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1xYmDJL80EwZ2FXa72X2Llw0yvVT1U2-kmPP0pJ8GvI8/edit#gid=0",
    "totalPending": 1276,
    "delayCount": 1163,
    "age": 478,
    "pcName": "Nisha Tripathi",
    "doerName": "Anuj Kumar Singh,Vikesh Kumar,Satyam Kumar,Biju.R,Sajeev K,Sanju U,Chithra C,Prakasan M,Mahesh,Vishnudas S,Karthik Kumar,Anilkumar C B,Gopi S,Vishnu Prasad S,Pushpanshu Kumar,Silpa V,Nagendran,Anju S,Deepthish K R,Sunaj Sahoo,SATISH CHANDRA GANGWAR,Krishnapriya K,Arun,Pawan Kamra,KAC Order Taker,Kiran Prasad,Manju S,Vinod M,Kavita (PC),Ambuj,S K THAKUR,Abhilash Sir,Deepratan Bande,Chandraprakash Parashar,Hemant Gaur,Rajendra Kumar,Tikam Chand Ashrani,Sameer Anand,Vijay Kumar,Suneel Kumar,Harish Mishra,Birender Singh Chauhan,Himanshu Kumar,Pradeep Gond,SAILESH KUMAR VERMA,VINAYAK PANDURANGA AMBIG,Kamal Sharma,RAVINDRAN B,Muthukumara Raja,Anoop Vijayaraj,Rahul Srivastava,Dhaneshwar Chaturvedi,Renuka K,Sujith S,Sivadas S,Sanoj M,Sadik Rehman,Thangarasu,Harpal Singh,Arvind Kumar Thakur,Arul,Astha Kumari,Puneet Endlay,Ashok Sharma,Krithika,Girish Chaturvedi,Shoukath Ali Moosa,Bhuvaneshwari,Ratheesh K R,Ritu Chawla,Jobin Abraham,Ashikha Raj,Dr. Rahul R,Bonny Thomas,Ravi Mishra,Sini Nair,Janardhanan M,Gaurav Saraswat,Arundas R,Prema Dhuri,Biju Rajakumaran,Shristi,Deepu Sahani,Sunil Gour,Kavita,Shona George,Santhosh,Rahul Raj P R,Lineesh N,Ajay,Hariharan,Vikash,Anupam Singh Molpha,Rahul Kumar Gupta",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:38",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "OTIF FMS- Primary",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1yQhdTSVs2kW0GISkA5o_qziBO3AWBBe-injSwmeSDyU/edit#gid=0",
    "totalPending": 234,
    "delayCount": 94,
    "age": 110,
    "pcName": "Kavita",
    "doerName": "Sanjay Yadav,Kavita",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:40",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "CRR Dispatch - Logistics Verify FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/16CxpUgn5LN2y9uh4CXaxUH3__eTX_k0C7Z33q0SwKwU/edit#gid=550544894",
    "totalPending": 259,
    "delayCount": 131,
    "age": 107,
    "pcName": "Krithika",
    "doerName": "Krithika,Nisha Tripathi,Kavita",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:41",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Pre Filling - PMS (Ayurvedic)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/17lyo7cBzIykgpqRNmesuCNuNLHWgDIPu-jk_Hiv9IA4/edit#gid=1365466913",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Sakthivel S",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Induction FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1w7pZdpvYQ8UfX1sRGN3yTldB9UnG8LpvSElwEB7KL3g/edit#gid=0",
    "totalPending": 43,
    "delayCount": 32,
    "age": 774,
    "pcName": "Krithika",
    "doerName": "Dhaneshwar Chaturvedi,Rakesh RajaGopal",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:43",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "POB Reorder (Planned) - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1DfXw6C2oNDHJe6784js4C5yrskQxOCDpnGU7JK22llY/edit#gid=0",
    "totalPending": 940,
    "delayCount": 940,
    "age": 95,
    "pcName": "Krithika",
    "doerName": "Krithika",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:43",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "QC & Store Purchase FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1AtirMtOPzUdE5IAbmLugxrgxde1eEnA8JZgzNApOWQ8/edit#gid=0",
    "totalPending": 297,
    "delayCount": 276,
    "age": 1078,
    "pcName": "Krithika",
    "doerName": "Balavignesh S,Nagendran,Sakthivel S,Arul,Ritu Chawla,Mathi Sekar",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:42:46",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Lost Client - FMS (POB)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1oZ4-EG_c7dYBPQyFGAeDRoczTY-_SxRlj4RA7pg7WDI/edit#gid=0",
    "totalPending": 279,
    "delayCount": 279,
    "age": 75,
    "pcName": "Krithika",
    "doerName": "Pushpanshu Kumar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:46",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "PrimarySales- Reorder Actual Sales FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1Bwg0TdCfv4kYcMG0euFjdzdKIH2PAA7VjDcMOIT7QV8/edit#gid=0",
    "totalPending": 3342,
    "delayCount": 3245,
    "age": 766,
    "pcName": "Krithika",
    "doerName": "Pushpanshu Kumar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:47",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Dispatch - FMS-FACTORY",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1CSQH6ieI442SSoTwewMafEHt6-MlIEUL2XMugrKwdI8/edit#gid=0",
    "totalPending": 964,
    "delayCount": 948,
    "age": 322,
    "pcName": "Krithika",
    "doerName": "Balavignesh S,Sathish Kumar S,Sakthivel S,Dinesh Kumar,Thangarasu,Arul,Manonmani",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:42:49",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "PrimarySales- Reorder Planned Sales FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/12r-64ymKaXOQMRlnDqrW8kyzJ8tVXDIAY75Y3qLywgs/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "New Order FMS- online & offline",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1woQUz1T8JdD8J6O4sxAlt8y8GVSDVFsJ9rjWiFAbXaM/edit#gid=211361608",
    "totalPending": 58,
    "delayCount": 45,
    "age": 37,
    "pcName": "Krithika",
    "doerName": "Sanjay Yadav,Krithika,Kavita,Sakthivel S,Manonmani",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:52",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Purchase Approval FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1flTGnAksRmfd2Jg7cui2WDLaPyfiGchPk1uupKfjKUk/edit#gid=0",
    "totalPending": 91,
    "delayCount": 86,
    "age": 54,
    "pcName": "Krithika",
    "doerName": "Jayan P C,Nagendran,Arul",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:52",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Complaint Tracker FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1vsKMutocf9n2Em_IYbgfHp_H8upmI_i5aV5RVAYt-tM/edit#gid=0",
    "totalPending": 4,
    "delayCount": 4,
    "age": 98,
    "pcName": "Krithika",
    "doerName": "Muthukumara Raja,Saravanakumar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:54",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Distributors Stock Statement & Ledger - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1_fzazW4S6nJIXxh0Hg7hQ1F4i3MfwHxhrV7kxBB5i-k/edit#gid=2142504557",
    "totalPending": 223,
    "delayCount": 190,
    "age": 75,
    "pcName": "Kavita",
    "doerName": "Krithika,Ajay,Ritu Chawla",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:42:55",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "2 - Pre Production FMS - Sanitizer",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1eBAnmgtz0IYIjWOvyl6PxpbfOinqmpLiCNudzp5oBLY/edit#gid=1908675745",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Mahesh,Ritu Chawla",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "POB False Order FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1Ip1IDX_MwP0xRKDlAUjqQhzKX2U10a7erJXTqXVhtn8/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Anuj Kumar Singh",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "PrimarySales- Lost Clients FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/12Gsc99sH10Pm1a-sR6PA_wf13dIIvWJzVxnpzqbcngE/edit#gid=0",
    "totalPending": 29,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Kavita,Sunaj Sahoo",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:02",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "PrimarySales- Alert Client's Tacker",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1CUXOs8aVDy4UOFZipZPBSsH-pYE0h54pb_qmmSSBOq8/edit#gid=1325439452",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Sunaj Sahoo",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "All Employee Handover FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1MvLg2gxjsM07QQEI6hWAG9PGT7oEHa_zMIEjtLpAqKk/edit#gid=0",
    "totalPending": 15,
    "delayCount": 1,
    "age": 55,
    "pcName": "Krithika",
    "doerName": "Dhaneshwar Chaturvedi,Anjana Sharma",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:03",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Job Opening - FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1m9G8QXSHMTRQ5brDRW15YX86wnODkmGL42x3trPa7CQ/edit#gid=868988170",
    "totalPending": 11,
    "delayCount": 11,
    "age": 151,
    "pcName": "Nisha Tripathi",
    "doerName": "Rakesh RajaGopal,Dhaneshwar Chaturvedi,Thangarasu",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:04",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Emp Onboarding - FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1h6TrFsQrdD2GDa5h5k2HxT0zvYUMRBhJL2RkHYqp57o/edit#gid=99086834",
    "totalPending": 10,
    "delayCount": 8,
    "age": 2,
    "pcName": "Nisha Tripathi",
    "doerName": "Dhaneshwar Chaturvedi,Krithika,Ritu Chawla",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:08",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "4 - Production PMS Sanitizer",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1d1v4aIUonLs-RKggWUZSfaRRjzF4vGJ3e5Pu3hTKGVc/edit#gid=2016100537",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "UDHAYANANDHINI A",
    "doerName": "KEERTHIKA DEVIan",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Collection Engine - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1cwTa-Ox4nVJXCAsa8tDYdyZqmK34jUYh2FtL4vgc1aw/edit#gid=0",
    "totalPending": 6445,
    "delayCount": 6117,
    "age": 2384,
    "pcName": "Kavita",
    "doerName": "Vigneshkumar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:14",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Kairali  Leave FMS For Field Staff",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1l-JWvIJno1X0yRrUjSPTaOiq4AMC9FFwc1AR3E62q_s/edit#gid=1265795625",
    "totalPending": 21,
    "delayCount": 19,
    "age": 80,
    "pcName": "Krithika",
    "doerName": "Deepratan Bande,Dhaneshwar Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:15",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Alert! Clients - POB",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/18Ftu1kOLx27-jVx2WP5k1L-fTIzQ-nr0hydpTU8-6eI/edit#gid=0",
    "totalPending": 34,
    "delayCount": 32,
    "age": 18,
    "pcName": "Nisha Tripathi",
    "doerName": "Krithika",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:15",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "POB BUYER VERIFY FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1h_fd1TTqkr3ta_VDCChDUf7Mb-R2d4CVmX2LssqK2AA/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Karan Pahuja",
    "important": true,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "3 -  Filling Machine Scheduler (Ayurvedic & Sanitizer)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1RuPY-5BCGiwSChFpW7l2T1HxR4b1mCGCZpY41YS9TSg/edit#gid=1659938490",
    "totalPending": 1,
    "delayCount": 1,
    "age": 42,
    "pcName": "Krithika",
    "doerName": "Balakrishna",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:21",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "KAPPL CAPA FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1wCC_fqChyTFJTW-PL-5x7tDvgLrqi-Clu9HlkzjBPhw/edit#gid=0",
    "totalPending": 2,
    "delayCount": 1,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Sanjay Yadav",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:43:22",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Employee Exit FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1-bD7FWG76BCdAXqS903MRFsBlO9ck2dfUdawhbXjjwY/edit#gid=99086834",
    "totalPending": 8,
    "delayCount": 6,
    "age": 55,
    "pcName": "Kavita",
    "doerName": "Dhaneshwar Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:22",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "2 -  Pre Production - PMS (Ayurvedic)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1eq3vzfDlitPaGjgKsy1Vy6t97X0xJW2wW1fRax7YqkY/edit#gid=249799369",
    "totalPending": 198,
    "delayCount": 198,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Mahesh,Ritu Chawla",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:43:48",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "3 -  Production Machine Scheduler (Ayurvedic)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/167bX9d_6oL2mSddA3UGWsWH7MG-x5rauMKY14vvmYUQ/edit#gid=1094130387",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Hariharan",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "3 - Production Machine Scheduler - Sanitizer V2 (New)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1LDnwYzhQ0U6iSjojf-JXiX-RexQoT3u2-qw78FwCQjM/edit#gid=604501152",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "ADC FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1Wu3lPGVwAZLGMjaFc_lDmGFcO4r4gBB0HEispV2yKGg/edit#gid=1954911606",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Ambuj",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Ajay-  Reseach Data FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1PQPxcAG18mlfCEWbkfI3tpmhqvupAz5f7teMW6FgcMk/edit#gid=119045762",
    "totalPending": 1,
    "delayCount": 1,
    "age": 63,
    "pcName": "Krithika",
    "doerName": "Ajay",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:44:09",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Calling FMS - Abhilash Sir",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1nnimRzJQamZppda-trURPMkXlHnvkNNV2Im1DqYa_9s/edit#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Calling FMS-VIKASH-Admin Enquiry",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/12KzlYsAU7o-3pgxcAxuN5-G0ucz-Iv4UsjIU4ScCqvc/edit#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Clients Details [Birthday, Anniversary etc] - Send Greetings",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/10VG51plPcsOX-tdf22908PRzSt7nIc8omYfrd8KB-oc/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "Error (https://docs.google.com/spreadsheets/d/10VG51plPcsOX-tdf22908PRzSt7nIc8omYfrd8KB-oc/edit#gid=0): You do not have permission to access the requested document.",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Daily consumption of Firewood, Electricity, Diesel & Labour",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1HZPQ0bIPT6fOTIcvon9vKxxvKHr9YKrd6xTZX3xx6iQ/edit#gid=419545027",
    "totalPending": 1360,
    "delayCount": 100,
    "age": 19,
    "pcName": "Krithika",
    "doerName": "Saravanakumar,Krithika,Mathi Sekar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:44:17",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "distributor IMS ADC FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/u/1/d/1nOnNND9kpk1YYjk254LVBrRfaw-d7TLi_PCaAWDwyoc/edit",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Ambuj",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Distributors Handover FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1Ibpixfz4KMrbF8reY2U_TOCTWL_BGFZ1I2kyZC8sIUc/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Distributors IMS OverStock - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1olVnvGg9fmodNY1EOBJN7cK8wJWQL4SgiEDweO3-CZs/edit#gid=537978483",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Sanjay Yadav",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Distributors IMS UnderStock - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1C9y_GbEJvN_1fpL_al19hQ23ZUGd19fKviE5PSqJGgk/edit#gid=537978483",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Sanjay Yadav",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "EMP-Joining Details Database",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/16eHVH8m6t0h34NNaIW7jiXtLeuEILzGw79ipV7xh05Q/edit?gid=0#gid=0",
    "totalPending": 32,
    "delayCount": 32,
    "age": 19,
    "pcName": "Kavita",
    "doerName": "Dhaneshwar Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:44:29",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "FMS- enquiry reserch again",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1UyeTwyduNx-ThH_KNiw-XI7Y_sXZIeyfKTxz-BZ93e8/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Ajay",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Himanshu -  Reseach Data FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1ABV4N4KvuIJhLrqsXpwdHZE0tXVlQ5rA9W_tlG4fk30/edit#gid=119045762",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "Error (https://docs.google.com/spreadsheets/d/1ABV4N4KvuIJhLrqsXpwdHZE0tXVlQ5rA9W_tlG4fk30/edit#gid=119045762): Service Spreadsheets timed out while accessing document with id 1ABV4N4KvuIJhLrqsXpwdHZE0tXVlQ5rA9W_tlG4fk30.",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Incentive FMS (POB)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1rjmT5dqh815EJnJTZphqaxSegXJfq27U3fUzpalJumI/edit#gid=1605747438",
    "totalPending": 60,
    "delayCount": 60,
    "age": 688,
    "pcName": "Krithika",
    "doerName": "Anuj Kumar Singh",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:14",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Inventoryturn FMS (Packaging Materials)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/15ZJiZz82TElJGNknwr0VUqumgm6AvfakZ4MvbHuVN14/edit#gid=13230382",
    "totalPending": 21,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Jayan P C",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:15",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Inventoryturn FMS (Raw Materials)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1VHqXj3-Pqc9p-I_SoGg0Jvlf8Hm-73fC9o4cAq9VYB8/edit#gid=13230382",
    "totalPending": 20,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Jayan P C",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:16",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "InventoryturnOver FMS (Finished Goods)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1nmb7Ke4bCX1AkBJhLeODISh-UuVf-xqyihihaUMSbdI/edit#gid=1527704363",
    "totalPending": 20,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Jayan P C",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:16",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Kairali Team Call Recordings - Audit FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/103QG3xJfTv0lWH1bOgmUdl9VnYQc2M4BxYm0Eeium9E/edit#gid=0",
    "totalPending": 1152,
    "delayCount": 1152,
    "age": 158,
    "pcName": "Krithika",
    "doerName": "Vikash",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:17",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Lead Time & Safety Factor-FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1Mrvm94cMrLH272r-OdazZPRa-tu8-lA6cGfvdVEiBOY/edit#gid=1718874142",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Hariharan,Sakthivel S",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Increment FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/14yN20o5jOIoMCkr7qK6m8fwhrqah3cZlCNaxOiqOMSM/edit#gid=0",
    "totalPending": 16,
    "delayCount": 14,
    "age": 57,
    "pcName": "Kavita",
    "doerName": "Dhaneshwar Chaturvedi,Anoop Vijayaraj,Jobin Abraham,Dr Deepu John,Abhilash Sir",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:19",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "IMS - PO Connect FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1Ib3KXEcx_aKSPBk1cBmshkhtd5YC7xhwND7sszvpPlE/edit#gid=1564335767",
    "totalPending": 137,
    "delayCount": 137,
    "age": 236,
    "pcName": "Krithika",
    "doerName": "Nagendran",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:20",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "New Delegation Sheet Master V2 - 2022",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/19MP_sEVE8JrC2hOMXbhhGDWTGCOcfoVTwLj0M422Di0/edit#gid=0",
    "totalPending": 3079,
    "delayCount": 2704,
    "age": 1049,
    "pcName": "Sunaina Bali",
    "doerName": "Anoop Vijayaraj,Ritu Chawla,Ambuj,Sunaj Sahoo,Gaurav Saraswat,RAVINDRAN B,Smita Ghai,Arul,Harpal Singh,Abhinav Sood,Satyam Kumar,Anuj Kumar Singh,Sony Cherian,Rajesh Arora,Pushpanshu Kumar,Vikash,Mona Walia,Jobin Abraham,Roshni A John,Nagendran,Astha Kumari,Suresh Kumar c,Deepu Sahani,Karan Pahuja,Sreehari R,Anupam Singh Molpha,Sadik Rehman,Santhosh,Dr Deepu John,Dr. Akhila Oommen,Ashikha Raj,Ajay,Rahul Raj P R,Silpa Sasi,Thangarasu,Pawan Kamra,Dhaneshwar Chaturvedi,Sunil Gour,Rohan Babbar,Abhilash Sir,Gaurav PPC,Trusha Lodhi,Sanjay Yadav,Rakesh RajaGopal,Shoukath Ali Moosa,Bonny Thomas,Bhuvaneshwari,kiran Raj,Abilash A,Sivadas S,Surjeet Kumar,M. Ajithkumar,Dr. Rahul R,Jinsha Manoj MV,Kiran Chauhan,Shadab Ali",
    "important": true,
    "timestamp": "",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "OTIF(POB) FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/17PBlfMlrG9006Qrr1IO_m-NnK_u7d1wMLM6wyGa3JVM/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "POB CAPA FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1sBAwlC4k3zt_qqozGCSfiz8G_IR1wtqd3G0yNwVGNNA/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sanjay Yadav",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "POB Dispatch FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/u/0/d/1cmAsdnQi8a092_9-UApp0x-hktS48rpbWTl0lP7fClY/edit",
    "totalPending": 295,
    "delayCount": 286,
    "age": 36,
    "pcName": "Kavita",
    "doerName": "Kavita Mahawar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:24",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "4 -  Production PMS (Ayurvedic)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1sQOas8fZzReXlvJkGcGZfEFxbabofr97Mvzb-YxhisY/edit#gid=2016100537",
    "totalPending": 205,
    "delayCount": 193,
    "age": 280,
    "pcName": "Krithika",
    "doerName": "Sakthivel S,Jayan P C,Balavignesh S",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:25",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Script ErrorHandling FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1m70lAPcxrPyCEVm4Vq7LgO6M09D5AJI59O3n6b1a0iQ/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Vikas -  Reseach Data FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1DBKv7aDo9VqbR3CUMK4HaZEWnELZH5ETqWZ7wKa2MHQ/edit#gid=119045762",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Calling Sheet - Sunaina Bali",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1KeGGsPT_dOv6n9j5KWpF_nDW-fL_WGRf_-LZ-B6yI-w/edit#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Calling Sheet - Kavita",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1_XsYrBmqo8ckHIhNI3jnHNby_-US8Ejh5WLseCckYZI/edit#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Calling Sheet - Krithika",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1sidW5IiGAIjNrTzojfxM5nHHpo8sF4tf75QfSmXROSU/edit#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Calling Sheet - Karan Pahuja",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1H09oNO7FNlbwRDIwH9El6y_Lr6GwkRCoIKnxokYBgLM/edit#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Guest Tracker FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1zWuoDnB-TyenkwNFWc3gPP4_fZOpInvV4ZJpZQm1ILQ/edit#gid=0",
    "totalPending": 96,
    "delayCount": 72,
    "age": 61,
    "pcName": "Kavita",
    "doerName": "Nishant,Admin,Harpal Singh,Levil Kumar,Pushpanshu Kumar,Sadik Rehman,Anoop Vijayaraj,Shoukath Ali Moosa",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:54:31",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Master Conversion sheet KAPPL & KTAHV",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/u/1/d/1ZUFUAEftWua37CJw4LIJUQVS1eqagt1WBvWQVlYdY1E/edit",
    "totalPending": 185,
    "delayCount": 49,
    "age": 227,
    "pcName": "Krithika",
    "doerName": "Kavita",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:32",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Calling Sheet - Bhuvaneshwari",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1TiOzFNoKdUJANHkXWyVHv5swYVTDrfLgQ8U7qxaLWx8/edit#gid=93793889&range=N54",
    "totalPending": 96,
    "delayCount": 11,
    "age": 16,
    "pcName": "Kavita",
    "doerName": "Bhuvaneshwari",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:35",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Verified Mining Lead Assign To MR - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1qEolCm0GVvr91QSdUkHN2SdUs8vzOuaOfWO3lBY8qIA/edit#gid=0",
    "totalPending": 4,
    "delayCount": 4,
    "age": 1,
    "pcName": "Kavita",
    "doerName": "Krithika",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:36",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Marketing Campaigns Expense FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1i1BAU32izr84H1qttPoc3DpZ_-ARQMxQ9P5qcGHBfIE/edit#gid=0",
    "totalPending": 72,
    "delayCount": 66,
    "age": 14,
    "pcName": "Kavita",
    "doerName": "Anuj Kumar Singh,Astha Kumari",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:37",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Golden Circle Clients (Primary Orders)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1V46XzWiUG1LBN7q6U-rRCYxZ9npSzUnI8Jq-85B66uc/edit#gid=801744041",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Bulk WhatsApp Reply - Enquiry Generation",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1dLA14qMTXvDtI_Zl98p7W4qAYFQlnLlak8UBXjADh50/edit#gid=0",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Sunaina Bali",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "KTAHV CRR Process FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1Zqulq3qFRYwGxKNKfF6gNVf4iua_DNYNTk0-4Bw8FVA/edit#gid=0",
    "totalPending": 37,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Dr. Rahul R",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:54:42",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "KTAHV CRR Calling FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1Nr8MdtjyXenAoKeX_n4sWa-T1_O9cqErLYXeQMHESOk/edit#gid=0",
    "totalPending": 51,
    "delayCount": 4,
    "age": 1,
    "pcName": "Kavita",
    "doerName": "Sheeji C,Dr. Rahul R,Shoukath Ali Moosa",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:54:43",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Incentive FMS (KTAHV)",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/13rlSYs-ALPmrVX_L-816akwNPcat4GYEqV6OpoZ9eR4/edit?usp=sharing",
    "totalPending": 618,
    "delayCount": 593,
    "age": 427,
    "pcName": "Karan Pahuja",
    "doerName": "Biju Rajakumaran,Anuj Kumar Singh,Dhaneshwar Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:44",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Calling Sheet  - Harpal Singh",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1Mp7pnbaddAvrjKk7lRhk5VORY_3LnwWB9MpiFT-bchs/edit#gid=93793889",
    "totalPending": 452,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Harpal Singh",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:54:45",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Resort CheckList FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1HZ3ifIeNxQBnthiycIo-_vKDzlqlCsA9vF-hmsuGajY/edit#gid=0",
    "totalPending": 163,
    "delayCount": 58,
    "age": 137,
    "pcName": "Karan Pahuja",
    "doerName": "Suresh Kumar c,Drisya M,Ratheesh K R,Karan Pahuja,Rahul Raj P R,Jobin Abraham,kiran Raj,Santhosh,Silpa Sasi,Shoukath Ali Moosa",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:46",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Help-Slip  (For Director)",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1nVhSYdhlq6tOJQRrvfN-y9vc3Cl4jTj8gBQmaRVZG1w/edit#gid=0",
    "totalPending": 148,
    "delayCount": 105,
    "age": 417,
    "pcName": "Kavita",
    "doerName": "Abhilash Sir,Ritu Chawla,Roshni A John,Sadik Rehman,Harpal Singh,Rohan Babbar,Chandraprakash Parashar,Nagendran,Kamal Sharma,Rahul Srivastava,Hemant Gaur,Sameer Anand,Vijay Kumar,SAILESH KUMAR VERMA,Avnish Kumar Dubey,Rajesh Arora,Puneet Endlay,Suneel Kumar,Tikam Chand Ashrani",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:50",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "- Deleted - Verified Mining Lead Assign To MR - FMS Sheet",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1PEABoWPAKGqyZYDCkRgk002Wd05Jas-tau7KyPyMuXM/edit?userstoinvite=svp.aashok%40gmail.com&sharingaction=manageaccess&role=writer#gid=695625658",
    "totalPending": 79,
    "delayCount": 79,
    "age": 870,
    "pcName": "Kavita",
    "doerName": "Krithika",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:51",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "SQV Not Qualified Lead Verify FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1a2SJ8g77cGhgkwWIfCqnzCgJBtw3bG5BrDnitQJVKTU/edit#gid=0",
    "totalPending": 3406,
    "delayCount": 3352,
    "age": 85,
    "pcName": "Kavita",
    "doerName": "Anupam Singh Molpha,Rohan Babbar,Astha Kumari,Vikash,Trusha Lodhi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:54:52",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Lead Time - FMS (FG/SFG)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/137O90D0ek1yhLPg2XAoZFBNWnen4qdertGVMpUYtS8c/edit#gid=972343956",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Ambuj",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Golden Circle FMS. (POB)",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1SciVrCYsa_1ALPqempLwgVxctIbHxpHBVfupHS_YOqc/edit?gid=1419913175#gid=1419913175",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Calling Sheet  - Zaki Ahmed",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1ihZmg3k0agrnN_jxY1c6AF8ZTxxyPsQNHuABFDXBepQ/edit?gid=93793889#gid=93793889",
    "totalPending": 333,
    "delayCount": 195,
    "age": 60,
    "pcName": "Kavita",
    "doerName": "Zaki Ahmed",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:55:02",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "ProfitMax Client Optimization - FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1nZ_eGwskAJnPWkn-HVvMz_A7mzYS-r7q6jl8SmlCvHk/edit?gid=990261588#gid=990261588",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Abhilash Sir",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Complaint Tracker - Head Office",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1j0SlOJDeWaolArBDuETH1wgLuSsleSBW8NaEfl256x0/edit?gid=1632531072#gid=1632531072",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Avinash Sahni,Sunaina Bali",
    "doerName": "Anuj Kumar Singh,Krithika",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "V2. NEW - FMS - MR Reporting Log",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/15R_I3lXtKXJiKqzgHERb0r9bSKmJugCsTny1-codUNw/edit?gid=0#gid=0",
    "totalPending": 308,
    "delayCount": 308,
    "age": 11,
    "pcName": "Krithika",
    "doerName": "Krithika,Dhaneshwar Chaturvedi",
    "important": true,
    "timestamp": "Updated at 15-07-2026 16:55:05",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "POB MR -  Other Expenses Verify FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1mT23Eh8FfR6rko5XdO4b9rut6SR3jb6Ek2mjPmt71UM/edit?gid=665586968#gid=665586968",
    "totalPending": 2,
    "delayCount": 2,
    "age": 12,
    "pcName": "Krithika",
    "doerName": "Dhaneshwar Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:05",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "POB MR - TA-DA-Other Expense - Final Release FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1eDL3FMup2hk3uTd4NrZ6X5CJ04gai36cNYIUlxelwhg/edit?gid=880267937#gid=880267937",
    "totalPending": 57,
    "delayCount": 27,
    "age": 14,
    "pcName": "Krithika",
    "doerName": "Dhaneshwar Chaturvedi,Anuj Kumar Singh",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:12",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Incentive FMS (POB) - Revised",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1nfUYMUWTC_ezn2i5daVAmXclmQvow86-cXhkdJb5tcQ/edit?gid=1605747438#gid=1605747438",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Anuj Kumar Singh,Sunaj Sahoo,Sanjay Yadav,Puneet Endlay",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Medical Camps Activity Log",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/15h5QMBLIBm9a-zwqeHGI7Yq2JCRE_U4RJ8xfhmmacZg/edit?gid=1588919974#gid=1588919974",
    "totalPending": 2,
    "delayCount": 2,
    "age": 390,
    "pcName": "Krithika",
    "doerName": "Deepratan Bande,Girish Chaturvedi",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:15",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Patient Notes Management System",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1Yr2FVzFOtH5xakJNRaeNPsE_x5O6VHnowP3UvUMxmmE/edit?gid=1764229658#gid=1764229658",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "Error (https://docs.google.com/spreadsheets/d/1Yr2FVzFOtH5xakJNRaeNPsE_x5O6VHnowP3UvUMxmmE/edit?gid=1764229658#gid=1764229658): Pending Dashboard sheet not found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Contract manufacturing Live FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1TL0pXxLfyxcMKB3zKLCLh6sA-wfnzyw7QnzdnaQPufg/edit?gid=1525505177#gid=1525505177",
    "totalPending": 264,
    "delayCount": 264,
    "age": 372,
    "pcName": "Krithika",
    "doerName": "Sathish Kumar S,Balavignesh S,Jayan P C,Hariharan",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:17",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "b2b CRR Follow-up System - KTAHV",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1VJNCXxat2bcItVqsvW24NT9aDwnthaTfqsN5R1KkWTY/edit?gid=1746731608#gid=1746731608",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Karan Pahuja",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "PIP Training FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/17tyRKrYXDS6uy7cTDxN5DLtM7Eff0SnWUdma8KImTMY/edit?gid=1277642349#gid=1277642349",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Induction FMS - KTAHV",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1w7pZdpvYQ8UfX1sRGN3yTldB9UnG8LpvSElwEB7KL3g/edit?gid=360718067#gid=360718067",
    "totalPending": 43,
    "delayCount": 32,
    "age": 774,
    "pcName": "Krithika",
    "doerName": "Dhaneshwar Chaturvedi,Rakesh RajaGopal",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:30",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Employee Incident Management System - FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/17NclTBrCSushAevchhwoVB9HDZDMVm9HU35EdselM4k/edit?gid=2009244191#gid=2009244191",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Anjana Sharma",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Anupam Singh Molpha - Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1vtyHAVJzxG2xB37V7JA36FjaVLtPBIiO1T9YwpJxTfI/edit?gid=93793889#gid=93793889",
    "totalPending": 34,
    "delayCount": 34,
    "age": 175,
    "pcName": "Nisha Tripathi",
    "doerName": "Anupam Singh Molpha",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:31",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "KTAHV Travel Agent - Registered - Contact Database FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1VqqdQ146xGiSUp0jfr8Xp9jxS6TW1FlDvGFLGNBVUVk/edit?gid=1607771725#gid=1607771725",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Anuj Kumar Singh",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Vikesh Kumar - Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1mEOsGRqxVB0fQp6HgTkfVeHHs7_u-oCcNbjOVk0upEc/edit?gid=93793889#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Vikesh Kumar",
    "important": true,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Call Recordings Mapping FMS",
    "company": "ALL",
    "url": "https://docs.google.com/spreadsheets/d/1uebxaQu16Ahwn7yKOx-H5gpxZ1AwkgMabKzwtK3ile4/edit?gid=0#gid=0",
    "totalPending": 76,
    "delayCount": 76,
    "age": 0,
    "pcName": "Krithika",
    "doerName": "Kavita",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:40",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "KTAHV - Payment Collection Verify FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1alnMYBVddEnUgBx1T12fiJkHZ72wbpYIVKhEVQTiz5s/edit?gid=2000248785#gid=2000248785",
    "totalPending": 261,
    "delayCount": 261,
    "age": 43,
    "pcName": "Kavita",
    "doerName": "Anuj Kumar Singh",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:40",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Vibin S- Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/14ZKfo5HJ9Fxfox9-_tSEzBuGUqUbntrCVwLIC2BKGSg/edit?gid=93793889#gid=93793889",
    "totalPending": 769,
    "delayCount": 769,
    "age": 280,
    "pcName": "Kavita",
    "doerName": "Anuj Kumar Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Production Variance Escalation FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1wcSMjpMgr2cWX_xnV9QqegFtSlxCR7eUOpXGgmh-FKc/edit?gid=0#gid=0",
    "totalPending": 23,
    "delayCount": 23,
    "age": 21,
    "pcName": "Krithika",
    "doerName": "Jayan P C",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:48",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Sample FMS",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/16g0I8clSh3j1sDlLa_x17o7VQT947V71HwXhNsjG7Gg/edit?resourcekey=&gid=1497791575#gid=1497791575",
    "totalPending": 35,
    "delayCount": 35,
    "age": 317,
    "pcName": "Kavita",
    "doerName": "Krithika",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:50",
    "dmeName": "Ambuj Mishra"
  },
  {
    "fmsName": "Sam K Alexander - Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/14ZKfo5HJ9Fxfox9-_tSEzBuGUqUbntrCVwLIC2BKGSg/edit?gid=93793889#gid=93793889",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "Kavita",
    "doerName": "Krithika",
    "important": false,
    "timestamp": "No relevant data found",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "1952069 - KTAHV SALES",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 21,
    "delayCount": 21,
    "age": 0,
    "pcName": "",
    "doerName": "Pawan Kamra, Sadik Rehman, Rohit Ahuja,Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "1895925 - KTAHV CRR SALES",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "3478520 - KTAHV COLD CALLING",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Pawan Kamra, Sadik Rehman, Rohit Ahuja,Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "6982003 - LANGUAGE BARRIER CALLS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 160,
    "delayCount": 160,
    "age": 0,
    "pcName": "",
    "doerName": "Pawan Kamra, Sadik Rehman, Rohit Ahuja,Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "8952381 - KTAHV FEEDBACK",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Pawan Kamra, Sadik Rehman, Rohit Ahuja,Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "9024207 - KTAHV REFERRAL",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Pawan Kamra, Sadik Rehman, Rohit Ahuja,Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "2903899 - KTAHV GUEST TREATMENT RESULT FOLLOW UP",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Pawan Kamra, Sadik Rehman, Rohit Ahuja,Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "2636490 - CRR SALES",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Vidisha Bahukhandi, Zaki Ahmed, Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "3188322 - KAPPL SALES",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 823,
    "delayCount": 823,
    "age": 0,
    "pcName": "",
    "doerName": "Pushpanshu Kumar, Vidisha Bahukhandi",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "5360814 - COLD CALLING",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Pushpanshu Kumar, Vidisha Bahukhandi",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "1602189 - VILLARAAG NBD SALES",
    "company": "VILLARAAG",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 9,
    "delayCount": 9,
    "age": 0,
    "pcName": "",
    "doerName": "Pawan Kamra, Sadik Rehman, Harpal Singh,Pushpanshu Kumar",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "9210949 - VILLARAAG CRR SALES",
    "company": "VILLARAAG",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 2,
    "delayCount": 2,
    "age": 0,
    "pcName": "",
    "doerName": "Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "2304280 - INTERNATIONAL KTAHV NBD B2C SALES",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "7548326 - INTERNATIONAL KTAHV NBD B2B SALES",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "7753340 - INTERNATIONAL KTAHV CRR B2C SALES",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "2256941 - INTERNATIONAL KTAHV CRR B2B SALES",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "5182670 - INTERNATIONAL KAPPL NBD B2C SALES",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 487,
    "delayCount": 487,
    "age": 0,
    "pcName": "",
    "doerName": "Pushpanshu Kumar, Vidisha Bahukhandi",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "2270288 - INTERNATIONAL KAPPL NBD B2B SALES",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 97,
    "delayCount": 97,
    "age": 0,
    "pcName": "",
    "doerName": "Pushpanshu Kumar, Vidisha Bahukhandi",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "6564477 - INTERNATIONAL KAPPL CRR B2C SALES",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 94,
    "delayCount": 94,
    "age": 0,
    "pcName": "",
    "doerName": "Pushpanshu Kumar, Vidisha Bahukhandi",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "4180275 - INTERNATIONAL KAPPL CRR B2B SALES",
    "company": "KAPPL",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 11,
    "delayCount": 11,
    "age": 0,
    "pcName": "",
    "doerName": "Pushpanshu Kumar, Vidisha Bahukhandi",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "4297892 - INTERNATIONAL VILLARAAG NBD B2C SALES",
    "company": "VILLARAAG",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "8562059 - INTERNATIONAL VILLARAAG NBD B2B SALES",
    "company": "VILLARAAG",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "8564458 - INTERNATIONAL VILLARAAG CRR B2C SALES",
    "company": "VILLARAAG",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 0,
    "delayCount": 0,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "2695541 - INTERNATIONAL VILLARAAG CRR B2B SALES",
    "company": "VILLARAAG",
    "url": "https://docs.google.com/spreadsheets/d/1BVzVFnWYomZrJKKEBxh49fN5ImH79XpDR8rhO20AjB4/edit?gid=365230694#gid=365230694",
    "totalPending": 1,
    "delayCount": 1,
    "age": 0,
    "pcName": "",
    "doerName": "Sadik Rehman, Harpal Singh",
    "important": false,
    "timestamp": "",
    "dmeName": "Sunaj Sahoo"
  },
  {
    "fmsName": "Levil Kumar - Calling Enquiry FMS",
    "company": "KTAHV",
    "url": "https://docs.google.com/spreadsheets/d/1S8I76kp1TyZgwpgYhYqk-2ZfJ_j5xtxHKNDtzFmCQN4/edit?gid=93793889#gid=93793889",
    "totalPending": 95,
    "delayCount": 13,
    "age": 54,
    "pcName": "Kavita",
    "doerName": "Levil Kumar",
    "important": false,
    "timestamp": "Updated at 15-07-2026 16:55:51",
    "dmeName": "Sunaj Sahoo"
  }
];
